# Generated by Django 3.1.3 on 2020-11-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('x_coordinate', models.BigIntegerField()),
                ('y_coordinate', models.BigIntegerField()),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identityDocumentNumber', models.PositiveIntegerField()),
                ('dateOfBirth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.PositiveIntegerField()),
                ('infectingVirus', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('isLocal', models.BooleanField()),
                ('location', models.ManyToManyField(to='hotzone.Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.patient')),
            ],
        ),
    ]
